INSERT INTO category (description) values ('American');
INSERT INTO category (description) values ('Italian');
INSERT INTO category (description) values ('Mexican');
INSERT INTO category (description) values ('Fast Food');
INSERT INTO category (description) values ('Indian');
INSERT INTO unit_of_measure (uom) values ('Teaspoon');
INSERT INTO unit_of_measure (uom) values ('Tablespoon');
INSERT INTO unit_of_measure (uom) values ('Cup');
INSERT INTO unit_of_measure (uom) values ('Pinch');
INSERT INTO unit_of_measure (uom) values ('Ounce');
INSERT INTO unit_of_measure (uom) values ('Dash');
INSERT INTO unit_of_measure (uom) values ('Pint');
INSERT INTO unit_of_measure (uom) values ('Each');