version: 2.1

jobs:
  build:
    working_directory: ~/repo/spring-pet-clinic


orbs:
  maven: circleci/maven@0.0.12

workflows:
  maven_test:
    jobs:
      - maven/test # checkout, build, test, and upload test results
